### ISSUE TITLE
Version 1.0 requirements tracker

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#229]
@Shopify/cloudplatform @kirs I'm creating this issue to track what a v1.0 of this gem might look like, particularly with regard to breaking changes we might like to make.

## Breaking changes

- [x] New name that doesn't infringe on the "Kubernetes" trademark (https://github.com/Shopify/kubernetes-deploy/issues/30)
- [x] Single CLI command with subcommands for deploy/run/restart/render (https://github.com/Shopify/kubernetes-deploy/issues/256)
- [x] [tentative] Deploy command renders ERB only when given a flag, or maybe never. (must use the render command we've split out; related to https://github.com/Shopify/kubernetes-deploy/issues/44)
- [x] Different exit status for failures and timeouts
- [ ] [nice to have] Support a config file that can be used in place of flags: https://github.com/Shopify/kubernetes-deploy/issues/301

## Features/fixes

- [x] accepts $stdin as template dir (https://github.com/Shopify/kubernetes-deploy/issues/410)
- [x] has separate renderer command (related externally contributed proposal: https://github.com/Shopify/kubernetes-deploy/pull/228)
- [x] supports all major resource types (https://github.com/Shopify/kubernetes-deploy/issues/46)
- [x] stable CI for all GA k8s versions >= 1.6 (https://github.com/Shopify/kubernetes-deploy/issues/226) 
- [x] generic CR support (https://github.com/Shopify/kubernetes-deploy/issues/128)
- [x] generic timeout override annotation (https://github.com/Shopify/kubernetes-deploy/pull/232)
- [ ] (nice to have) generic monitoring opt-out annotation (related: https://github.com/Shopify/kubernetes-deploy/pull/208)
- [x] warning for unsupported k8s versions (https://github.com/Shopify/kubernetes-deploy/issues/152)
- [x] Use $TASK_ID as deploy ID if available (i.e when running in Shipit)  (https://github.com/Shopify/kubernetes-deploy/issues/136)
- [x] Support selector-restricted pruning / sub-namespace deploys (https://github.com/Shopify/kubernetes-deploy/issues/411 / https://github.com/Shopify/kubernetes-deploy/pull/235)
- [x] Support AWS EKS (https://github.com/Shopify/kubernetes-deploy/issues/396 / https://github.com/Shopify/kubernetes-deploy/issues/406)
- [x] Make `ENV[REVISION]` optional (https://github.com/Shopify/kubernetes-deploy/issues/351)
- [x] (required) Add docs for the public interface of the tasks, to make them easier to use from Ruby (https://github.com/Shopify/kubernetes-deploy/issues/105) 
- [x] (required) Rework the `Service` class to correctly handle the various types of services that are possible (https://github.com/Shopify/kubernetes-deploy/issues/265, https://github.com/Shopify/kubernetes-deploy/issues/483)
- [x] Make sure our prune whitelist includes all appropriate supported resources (https://github.com/Shopify/kubernetes-deploy/issues/271)
- [x] Make sure all resources support the timeout override annotation (https://github.com/Shopify/kubernetes-deploy/issues/315)
- [x] (required) Give all of our tasks a consistent set of preflight validations (https://github.com/Shopify/kubernetes-deploy/issues/344)

**Comment by benlangfeld** [comment]
> * Use $TASK_ID as deploy ID if available (i.e when running in Shipit)  (#136)
> * Make `ENV[REVISION]` optional (#351)

These two are complete.

**Comment by benlangfeld** [comment]
> * accepts $stdin as template dir (#410)
> * Support selector-restricted pruning / sub-namespace deploys (#411 / #235)

These two are also now complete.
